spring.data.mongodb.uri=mongodb://localhost:27017/fuel_delivery_db
server.port=8080
spring.application.name=fuel-delivery-system
server.port=${PORT:8080}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.uri=mongodb+srv://manideep1515:<db_password>@cluster0.zqimbww.mongodb.net/?appName=Cluster0